#!/bin/bash

# "Peirsman, Y.and Pado, S. 2011" no space before 'and' ?

function is_authors_list () {
    echo "$*" | tr '[]' '()' | grep -o "[()]" > /dev/null && return 1 # no ()[] characters
    echo "$*" | sed 's/and /,/g' | tr ";," '\n' | while read name; do # split according to ;, as well as 'and'
	is_author_name "$name" || return 1
    done && return 0
}

function is_author_name () {
    test $(echo "$*" | \grep -o "\ [a-z]" | wc -l) -ge 2 && return 1 # Too many lower case letters as first word letter
    test $(echo "$*" | wc -w) -gt 5 && return 1                      # More than >5 words ?
    echo "$*" | grep -E "(:|[0-9])" > /dev/null && return 1              # no numbers or ':'
    echo "$*" | grep -E " [a-z][^ ]*$" > /dev/null && return 1                   # Last word in lower case
    (echo "$*" | grep -E " (in|a|the|of|for|on) " > /dev/null) && return 1               # forbidden subwords
    return 0
}

function get_authors () {
    authors="$(echo "$*" | sed "s/\[.*\]//g")"
    authors="$(echo $authors | perl -ape "s/^(.*?[a-z][^ ]*)\..*/\1/g")"  # everything before first suspicious dot: '[a-z].' (must also catch "é."
    authors="$(echo $authors | perl -ape "s/:.*//g")"  # everything before first ':'
    # Use the 'and' marker somehow ?
    for i in $(seq 2 $((2+$(echo "$authors" | grep -o ',' | wc -l)))); do
        is_authors_list "$(echo $authors | cut -d "," -f $((i-1))-$i)" || break
    done
    authors="$(echo $authors | cut -d "," -f 1-$((i-1)))"
    test -z "$authors" && return 1
    is_authors_list "$authors" && echo "$authors" && return 0
    return 1
}
