#!/bin/bash

function get_journal () {
    journal="$(echo "$*" |
                   perl -ape "s/.*[,\.]\ *(.*?Journal .*?)\ [\.,].*/\1/g" |
                   perl -ape "s/.*[,\.]\ *(.*?Bulletin .*?)\ [\.,].*/\1/g" |
                   perl -ape "s/.*[,\.]\ *(.*?In .*?)\ [\.,].*/\1/g" |
                   perl -ape "s/.*[,\.]\ *(.*?[[:upper:]]+[[:lower:]]*\..*?)\ [\.,].*/\1/g" |
                   perl -ape "s/^.*?[,]\ *(.*?)[,].*/\1/g" |
                   tr -d "[0-9],[]():–" |
                   perl -ape "s/\ +\.//g" |
                   sed 's/^ +//' | sed 's/\ +$//' |
		   cat)"
    test -z "$journal" && return 1                                # Empty
    echo "$journal" | grep "^[[:lower:]]" > /dev/null && return 1 # Starts with lower case ?
    echo "$journal"
}
