#!/bin/bash

export VERBOSE=0

source find_authors
source find_title

# Extract the text if pdf input
file="$*"
if [ "${file:0:4}" == "http" ]; then
    tmp="$(mktemp  --suffix='.pdf')"
    wget -q --show-progress "$file" -O "$tmp" || exit 0
    file="$tmp"
fi

# Extract the text if pdf input
extension=$(echo "$file" | sed "s/.*\.//g")
if [ "$extension" = "pdf" ]; then
    tmp="$(mktemp  --suffix='.txt')"
    pdftotext "$file" "$tmp" || exit 0
    file="$tmp"
fi

# Cool case when all references start with [number]
./find_bibentries "$file" | tee /tmp/whatever_tmp | # filter ^[number] (remplacer par [alphanum_sans_espaces*])
    while read l; do

	# Authors
	authors="$(get_authors "$l")"
	if [ $? == 1 ]; then
	    test $VERBOSE == 1 && echo "Failure (authors): $l" 1>&2
	    continue
	fi

	remainder="$(echo "${l#*${authors}}" | sed "s/^[\.,: ]*//g")"

	# Title
	title="$(get_title "$remainder")"
	if [ $? == 1 ]; then
	    test $VERBOSE == 1 && echo "Failure (title): $remainder" 1>&2
	    continue
	fi

	echo "$title"
	echo "    (by) $authors"
	echo
    done

echo "(Uncaught refs) $((diff <(grep -o "\[[a-zA-Z]*[0-9]*\]" "$file" | sort -u) <(grep -o "\[[a-zA-Z]*[0-9]*\]" "/tmp/whatever_tmp" | sort -u)) | grep "^< " | tr -d '\n< ')" 1>&2
echo "(txt source) $file" 1>&2
