#!/bin/bash

grep "journal=" | grep "title=" | grep "pages=" |
    while read a; do
	p="$(echo "$a" | perl -ape "s/^.*╠pages=([^╣]*–[^╣]*)╣.*$/\1/g")"
	j="$(echo "$a" | perl -ape "s/^.*╠journal=([^╣]*)╣.*$/\1/g")"
	t="$(echo "$a" | perl -ape "s/^.*╠title=([^╣]*)╣.*$/\1/g")"
	echo "$p | $t╣╠$j"
    done | sort |
    while read l; do
	  b2="$(echo "$l" | sed "s/╣╠.*//g")"
	  t2="$(echo "$l" | sed "s/.*╣╠//g")"
	  if [ "$b1" = "$b2" ] && [ "$t1" != "$t2" ]; then
	      echo "$t1 | $t2";
	  fi
	  b1="$b2"
	  t1="$t2"
    done
