#!/bin/bash

echo "About to remove directory 1-meta/. Control+C if you don't want to, and press enter otherwise"
read
rm -rf "1-meta"
mkdir "1-meta"
wget -q --show-progress "http://export.arxiv.org/api/query?search_query=all:cs.AI&start=0&max_results=10" -O "1-meta/first"

tot="$(grep "opensearch:totalResults" "1-meta/first" | perl -ape "s/^.*>([0-9]*)<.*/\1/g")"
echo "$tot entries to download."
step=1000
for i in $(seq 0 $step $((tot-1))); do
    sleep 20s
    while ! wget -q --show-progress "http://export.arxiv.org/api/query?search_query=all:cs.AI&start=$i&max_results=$step" -O "1-meta/$(printf "%010d\n" $i)"; do
	sleep 20s
    done
done
rm "1-meta/first"
