#!/bin/bash

cat meta/* | grep "link title=.pdf." | grep -o "http://[^\"]*" | sort -u | while read l; do
    target="pdf/$(basename "$l").pdf"
    test -e "$target" && echo "(skipping) $l" && continue
    sleep 1s
    while ! wget -q --show-progress "$l" -O "$target"; do
	sleep 30s
    done
done
