#!/bin/bash
rm -rf "4-bibs"
mkdir -p "4-bibs"
for f in 3-txt/*; do
    i="$(basename "$f")"
    target="4-bibs/${i%.txt}.bib"
    if [ ! -f "$target" ]; then
	echo ../find_bibentries "$f" \> "$target";
    fi
done | parallel
