#!/bin/bash

mkdir -p "5-journals"
for f in 4-bibs/*; do
    i="$(basename "$f")"
    target="5-journals/${i%.bib}.txt"
    if [ ! -f "$target" ]; then
	echo ./4-bib_to_journal "$f" \> "$target";
    fi
done | parallel

minoccur=50 # Y'a vraiment des conneries (e.g. 'and', 'Math') qui ont >50 occurrences

cat 5-journals/* |
    tee 5-cat_journals | # Store all journal entries
    sort | uniq -c | sort -r -n |
    tee 5-sorted_journals | # Store sorted journals
    while read occ j; do
	if [ $occ -ge $minoccur ]; then
	    echo $j
	fi
    done |
    cat > 5-frequent_journals

f="unexplained_entries"
cat 4-bibs/* > $f
cat 5-frequent_journals | while read l; do
    grep -v ", *$l" "$f" > "${f}2"
    mv "${f}2" "${f}"
done
