#!/bin/bash

rm -rf "5-journals" "5-cat_journals" "5-sorted_journals" "5-frequent_journals"
mkdir -p "5-journals"
for f in 4-bibs/*; do
    i="$(basename "$f")"
    target="5-journals/${i%.bib}.txt"
    if [ ! -f "$target" ]; then
	echo ./4-bib_to_journal "$f" \> "$target";
    fi
done | parallel

minoccur=50 # Y'a vraiment des conneries (e.g. 'and', 'Math') qui ont >50 occurrences

echo "Building list of frequent (>$minoccur occurrences) journals"
cat 5-journals/* |
    tee 5-cat_journals | # Store all journal entries
    sort | uniq -c | sort -r -n |
    tee 5-sorted_journals | # Store sorted journals
    while read occ j; do
	if [ $occ -ge $minoccur ]; then
	    echo $j
	fi
    done |
    cat > 5-frequent_journals
